import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "@flatpacker/ui/globals.css";
import { Sidebar } from "@flatpacker/ui/composites";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="grid grid-cols-[64px_auto]">
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
